[project]
name = "marimo-nb"
version = "0.1.0"
description = ""
authors = [
    {name = "Lucio Dias",email = "luciodiass@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "marimo[recommended] (>=0.23.16,<0.24.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
